"""Add many-to-many relationship between User and Politician

Revision ID: 59bedac08522
Revises: 2f2bf01c8361
Create Date: 2024-05-28 21:38:35.444169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59bedac08522'
down_revision: Union[str, None] = '2f2bf01c8361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_politicians',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('politician_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_index('ix_answers_id', table_name='answers')
    op.drop_table('answers')
    op.drop_index('ix_questions_id', table_name='questions')
    op.drop_index('ix_questions_title', table_name='questions')
    op.drop_table('questions')
    op.add_column('users', sa.Column('favorite_politicians', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_politicians')
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_questions_title', 'questions', ['title'], unique=False)
    op.create_index('ix_questions_id', 'questions', ['id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_answers_id', 'answers', ['id'], unique=False)
    op.drop_table('user_politicians')
    # ### end Alembic commands ###
