/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/495txkYO5Hb
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Progress } from "@/components/ui/progress"

export function MemberInfo() {
  return (
    <div className="max-w-4xl mx-auto my-10 p-6 bg-white shadow rounded-lg">
      <div className="mb-6 p-4 bg-gray-200 rounded">
        <div className="space-y-2">
          <div className="text-lg font-semibold">Name: Kim Namjoon</div>
          <div className="text-lg">Position: Leader</div>
          <div className="text-lg">Birthday: 1994.09.12</div>
          <div className="text-lg">MBTI: ENFP</div>
          <div className="text-lg">Hobby: Reading Books</div>
        </div>
      </div>
      <div className="my-6">
        <div className="mb-4">
          <Progress value={76} className="w-full" />
          <div className="mt-1 flex justify-between">
            <span className="text-sm font-medium text-gray-700">Leadership</span>
            <span className="text-sm font-medium text-gray-700">76%</span>
          </div>
        </div>
        <div>
          <Progress value={66} className="w-full" />
          <div className="mt-1 flex justify-between">
            <span className="text-sm font-medium text-gray-700">Creativity</span>
            <span className="text-sm font-medium text-gray-700">66%</span>
          </div>
        </div>
      </div>
      <div className="border rounded-lg p-4">
        <h3 className="text-lg font-semibold mb-3">News</h3>
        <p className="text-gray-700">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua.
        </p>
      </div>
    </div>
  )
}
